name: Run Forex Pipeline

on:
  schedule:
    - cron: '0 9 * * *'   # 09:00 UTC
    - cron: '0 12 * * *'  # 12:00 UTC
    - cron: '0 14 * * *'  # 14:00 UTC
    - cron: '0 18 * * *'  # 18:00 UTC

  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    env:
      TWELVE_DATA_API_KEY: ${{ secrets.TWELVE_DATA_API_KEY }}
      PG_HOST: ${{ secrets.PG_HOST }}
      PG_PORT: ${{ secrets.PG_PORT }}
      PG_DB: ${{ secrets.PG_DB }}
      PG_USER: ${{ secrets.PG_USER }}
      PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      GSPREAD_KEY_JSON: ${{ secrets.GSPREAD_KEY_JSON }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run pipeline
        run: python forex_pipeline.py
